# Generated by Django 4.1.5 on 2023-01-07 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_todo_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='post',
        ),
    ]
