# Generated by Django 4.1.5 on 2023-01-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_todo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='completed',
            new_name='sold',
        ),
    ]
